### PR TITLE
Add unit test coverage reporting

### PR DESCRIPTION
**Pull request by socsieng**
Example output: https://github.com/opennextjs/opennextjs-aws/actions/runs/11415198269#summary-31764988744

image

### CODE REVIEW

**Comment by conico974** [comment]
Do we want to add this ?
That's great when you can achieve good coverage but given the code we have, i don't think it make that much sense.
cc @khuezy

**Comment by conico974** [comment]
@socsieng Wait is it only on the action that this appear or on the PR as well ?
If it's on the action only forget my comment

**Comment by socsieng** [comment]
> Do we want to add this ? That's great when you can achieve good coverage but given the code we have, i don't think it make that much sense. cc @khuezy

I thought it could serve as a reminder to include tests for future contributions

**Comment by conico974** [comment]
> > Do we want to add this ? That's great when you can achieve good coverage but given the code we have, i don't think it make that much sense. cc @khuezy
> 
> I thought it could serve as a reminder to include tests for future contributions

That's a good point, but given how some stuff cannot be unit tested i wonder if it won't make people try to write test and us having to ask to remove them and having to explain this everytime.

Or maybe it won't have any effect, the changeset bot as been there for a while and almost no PR contains a changeset :joy: 

Btw i've checked it doesn't work right now because the GH action don't have the permission to write PR

**Comment by socsieng** [comment]
> Btw i've checked it doesn't work right now because the GH action don't have the permission to write PR

I noticed that too. I set the permissions in the workflow file but I'm guessing it's related to my permissions on this repository.

I tested it out on my fork and it works as expected: https://github.com/socsieng/open-next/pull/1#issuecomment-2423790167

It might work for subsequent pull requests after merge... 🤞

**Review by khuezy — COMMENTED** [review]
Hey sorry I missed the ping here. LGTM Thanks!

The coverage report is nice but we shouldn't get too discouraged by the coverage numbers. 100% coverage is a trap!

**Pull request merged**
