### PR TITLE
fix: add more reliable sources to the revalidate e2e test

### PR DESCRIPTION
**Pull request by sommeeeer**
This PR adds more reliable sources to the fetches in `revalidateTag.test.ts` e2e

### CODE REVIEW

**Review by khuezy — COMMENTED** [review]
We're on next 15 now correct? If so, fetch by default doesn't cache, so I don't think this e2e would test for the revalidate since the amz-id would be unique on each request.

**Comment by sommeeeer** [comment]
> We're on next 15 now correct? If so, fetch by default doesn't cache, so I don't think this e2e would test for the revalidate since the amz-id would be unique on each request.

yeah we are on 15, forgot about the new beautiful cache behaviour. however, you can see the behavior yourself too: [`/revalidate-path`](https://dz1qocqqyz45x.cloudfront.net/revalidate-path)
[`/api/revalidate-path`](https://dz1qocqqyz45x.cloudfront.net/api/revalidate-path)

for some reason its working as it was next 14. maybe its something im missing thats completely obvious here. need to dig more into it

**Comment by sommeeeer** [comment]
yeah so the fetch caches is not cached by default, but our page is. we are modifying the cache headers on `/revalidate-path` in the middleware, so CloudFront doesn't cache it. The page is SSG still, so if I add `export const dynamic = `force-dynamic` to the top, you can see that the fetches is still not cached. I'll put this into draft, so I can work on fixing this.

**Comment by sommeeeer** [comment]
alright, so this one was a bit confusing at first, but it must be related to the fact [#L46-L54](https://github.com/opennextjs/opennextjs-aws/blob/1c271709497708d393e35f1fb5cfe78ca0f955f2/examples/app-router/middleware.ts#L46-L54) made me think this route is not SSG. 

since `/revalidate-path` is actually SSG, you can see that by looking at the `x-nextjs-cache` header being `HIT` and in the build log.

so each visit to `/revalidate-path` would still show the fetches as they were cached, but thats just because the page is static. triggering `revalidatePath("/revalidate-path")` would revalidate the entire page and thus also the fetches. 

therefor we need to add `export const dynamic = "force-dynamic"` on top of this page and also `force-cache` on the fetches to get the caching-behavior we are aiming for. 

this made me realize tho, should we maybe rework this a bit?

**Comment by conico974** [comment]
> therefor we need to add export const dynamic = "force-dynamic" on top of this page and also force-cache on the fetches to get the caching-behavior we are aiming for.

That's not the point of this test. We test that it revalidate the page not the fetch cache.

We may want to add a new e2e test to test the fetch cache behavior, but it's likely broken again in Next 15.
We could just cache those fetch here and add other test. (I'm surprised that the codemod did not change that to use caching, seems weird)

**Comment by sommeeeer** [comment]
> That's not the point of this test. We test that it revalidate the page not the fetch cache.

alright, so i guess i can just keep the code as it is for now, and in a future PR add another one for the fetch cache.

**Review by conico974 — APPROVED** [review]
LGTM Thanks

**Pull request merged**
